<HTML>
<head>
<link rel="stylesheet" href="raw.review.min.css">

</head>
<BODY>
<div id="reviewSteps" class="review_steps clearfix append_bottom15 ng-scope">
		<div class="review_borderbottom">
			<p class="review_steps_info">
				<span class="step_left tobe_select"> <span class="block step_icon"><font color="blue">1</font></span> <span class="block step_icon_select"></span> <span class="block step_label"><font color="blue">REVIEW</font></span>
				</span> <span class="step_center tobe_select" ng-click="validateReviewForm('traveller');">
					<span class="block step_icon">2</span> <span class="block step_icon_select"></span> <span class="block step_label">TRAVELLERS</span>
				</span> <span class="step_right tobe_select"> <span class="block step_icon">3</span> <span class="block step_icon_select"></span> <span class="block step_label">PAYMENTS</span>
				</span>

			</p>

		</div>
	</div>
	</BODY>
	</HTML>